version: '3.8'

services:
  devices-api:
    build: .
    container_name: devices_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=DevicesDb;User=sa;Password=Qasim@123;TrustServerCertificate=true;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: devices_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Qasim@123
    ports:
      - "1433:1433"
